In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

In [4]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
model = nn.Linear(1,1)

In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [12]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))
    

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [13]:
new_var = torch.FloatTensor([4.0])
pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값 : ", pred_y)

훈련 후 입력이 4일 때의 예측값 :  tensor([7.9989], grad_fn=<AddBackward0>)


In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## 다중 선형회귀 구현하기

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [17]:
torch.manual_seed(1)

In [27]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [28]:
model = nn.Linear(3,1)

In [29]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.5435,  0.3462, -0.1188]], requires_grad=True), Parameter containing:
tensor([0.2937], requires_grad=True)]


In [30]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [42]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    optimizer.zero_grad()    
    cost.backward()   
    optimizer.step()
    
    if epoch % 100 == 0:    
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 0.238494
Epoch  100/2000 Cost: 0.238091
Epoch  200/2000 Cost: 0.237695
Epoch  300/2000 Cost: 0.237311
Epoch  400/2000 Cost: 0.236918
Epoch  500/2000 Cost: 0.236531
Epoch  600/2000 Cost: 0.236137
Epoch  700/2000 Cost: 0.235750
Epoch  800/2000 Cost: 0.235369
Epoch  900/2000 Cost: 0.234995
Epoch 1000/2000 Cost: 0.234616
Epoch 1100/2000 Cost: 0.234240
Epoch 1200/2000 Cost: 0.233867
Epoch 1300/2000 Cost: 0.233486
Epoch 1400/2000 Cost: 0.233120
Epoch 1500/2000 Cost: 0.232747
Epoch 1600/2000 Cost: 0.232379
Epoch 1700/2000 Cost: 0.232019
Epoch 1800/2000 Cost: 0.231650
Epoch 1900/2000 Cost: 0.231287
Epoch 2000/2000 Cost: 0.230926


In [43]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.3107]], grad_fn=<AddmmBackward0>)


In [44]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9033, 0.4519, 0.6518]], requires_grad=True), Parameter containing:
tensor([0.3321], requires_grad=True)]
