In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [6]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [7]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [8]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [9]:
W = torch.zeros(1, requires_grad=True) # requires_grad 변수는 학습을 통해 계속 값이 변경되는 함수임을 의미
print(W)

tensor([0.], requires_grad=True)


In [10]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [11]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [12]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [13]:
optimizer = optim.SGD([W, b], lr=0.01)

In [16]:
nb_epochs = 1999
for epoch in range(nb_epochs + 1):
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f}, Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  100/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  200/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  300/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  400/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  500/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  600/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  700/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  800/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch  900/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1000/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1100/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1200/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1300/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1400/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1500/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1600/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1700/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1800/1999 W: 2.000, b: 0.000, Cost: 0.000000
Epoch 1900/1999 W: 2.000, b: 0.

optimizer.zero_grad()가 필요한 이유

In [19]:
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    
    z = 2*w

    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [20]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [21]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [22]:
torch.manual_seed(3)
print('랜덤 시드가 다시 3일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 다시 3일 때
tensor([0.0043])
tensor([0.1056])
