In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
model = nn.Sequential(nn.Linear(2,1),
                      nn.Sigmoid())

In [5]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [9]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost {:.6f} Accuracy {:2.2f}'.format(epoch, nb_epochs,cost.item(),accuracy * 100 ))

Epoch    0/1000 Cost 0.527002 Accuracy 83.33
Epoch   10/1000 Cost 0.994597 Accuracy 66.67
Epoch   20/1000 Cost 0.570399 Accuracy 83.33
Epoch   30/1000 Cost 0.473909 Accuracy 83.33
Epoch   40/1000 Cost 0.388606 Accuracy 83.33
Epoch   50/1000 Cost 0.307901 Accuracy 83.33
Epoch   60/1000 Cost 0.235923 Accuracy 83.33
Epoch   70/1000 Cost 0.182916 Accuracy 100.00
Epoch   80/1000 Cost 0.155795 Accuracy 100.00
Epoch   90/1000 Cost 0.143031 Accuracy 100.00
Epoch  100/1000 Cost 0.133369 Accuracy 100.00
Epoch  110/1000 Cost 0.124978 Accuracy 100.00
Epoch  120/1000 Cost 0.117600 Accuracy 100.00
Epoch  130/1000 Cost 0.111060 Accuracy 100.00
Epoch  140/1000 Cost 0.105223 Accuracy 100.00
Epoch  150/1000 Cost 0.099983 Accuracy 100.00
Epoch  160/1000 Cost 0.095251 Accuracy 100.00
Epoch  170/1000 Cost 0.090958 Accuracy 100.00
Epoch  180/1000 Cost 0.087044 Accuracy 100.00
Epoch  190/1000 Cost 0.083461 Accuracy 100.00
Epoch  200/1000 Cost 0.080169 Accuracy 100.00
Epoch  210/1000 Cost 0.077132 Accuracy 10

In [10]:
model(x_train)

tensor([[2.7553e-04],
        [3.1567e-02],
        [3.8923e-02],
        [9.5627e-01],
        [9.9824e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [11]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2543, 1.5186]], requires_grad=True), Parameter containing:
tensor([-14.4881], requires_grad=True)]
